# Generated by Django 3.2.9 on 2021-12-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galaxy',
            options={'verbose_name_plural': 'Galaxy'},
        ),
        migrations.RemoveField(
            model_name='galaxy',
            name='constellation',
        ),
    ]
