# Generated by Django 3.2.9 on 2021-12-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelestrialBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Celestrial Body',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('age', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'System',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('nickname', models.CharField(max_length=254)),
                ('surface_area', models.IntegerField(default=999)),
                ('age', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('celestrial', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='celestrial', to='space.celestrialbody')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galaxy', to='space.galaxy')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='space.system')),
            ],
            options={
                'verbose_name_plural': 'Entity',
            },
        ),
    ]
