# Generated by Django 3.2.9 on 2021-12-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("space", "0002_celestrialbody_entity_system")]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="constellation",
            field=models.CharField(default="cygnus", max_length=254),
        )
    ]
