# Generated by Django 3.2.9 on 2021-12-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('age', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galaxy', to='space.galaxy')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='space.system')),
            ],
            options={
                'verbose_name_plural': 'Pystem',
            },
        ),
    ]
