# Generated by Django 3.2.9 on 2021-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_planet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='nickname',
            field=models.CharField(default='planet', max_length=254),
        ),
        migrations.AddField(
            model_name='system',
            name='surface_area',
            field=models.IntegerField(default=999, max_length=254),
        ),
    ]
