# Generated by Django 3.2.9 on 2021-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20211208_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='surface_area',
            field=models.IntegerField(default=999),
        ),
    ]
