# Generated by Django 3.2.9 on 2021-12-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_alter_system_surface_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='system',
            name='surface_area',
        ),
        migrations.AddField(
            model_name='planet',
            name='nickname',
            field=models.CharField(default='planet', max_length=254),
        ),
        migrations.AddField(
            model_name='planet',
            name='surface_area',
            field=models.IntegerField(default=999),
        ),
    ]
