# Generated by Django 3.2.9 on 2021-12-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_auto_20211208_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
