# Generated by Django 3.2.9 on 2021-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0009_alter_planet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
