# Generated by Django 3.2.9 on 2021-12-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_alter_planet_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planet',
            new_name='Entity',
        ),
    ]
